---
- name: Verify
  hosts: all
  vars:
    pyenv_python_versions:
      - version: 3.7.7
      - version: 2.7.8
        state: absent
      - version: 3.8.3
        global: yes
    pyenv_dir: ~/.pyenv
  tasks:
    - name: get python versions
      command: >-
        {{ pyenv_dir }}/bin/pyenv versions
      register: pyenv_versions
      changed_when: false

    - name: check installed versions
      assert:
        that:
          - "'* 3.8.3' in pyenv_versions.stdout"
          - "'3.7.7' in pyenv_versions.stdout"
          - "'2.7.8' not in pyenv_versions.stdout"

    - name: check installed versions
      assert:
        that:
          - "'* 3.8.3' in pyenv_versions.stdout"
          - "'3.7.7' in pyenv_versions.stdout"
          - "'2.7.8' not in pyenv_versions.stdout"
